### ISSUE TITLE
Make scripts broken

### ISSUE THREAD

**Issue by izlatanov** [f5devcentral/f5-icontrol-library-java#1]
Hi,

just downloaded release 11.6.0 and attempted to build the thing on Windows. It first hit me that there are 2 make files - make.cmd and makenew.cmd. Which one to use? If makenew.cmd is the latest, why including both in the release? Quite confusing. Next, both make files contain absolute paths - to Java, to some jars, etc; these paths of course are not valid on any machine other than yours. No instructions provided where to replace what. Is this project for real at all?

Note to others that may need to build the source: do not use makenew.cmd, it is broken even worse than make.cmd - compiles only part of the sources: for %%s in (_icall_.java)

Ivaylo

**Comment by joepruitt** [comment]
The binary distribution for the libraries is available on DevCentral at https://devcentral.f5.com/d/icontrol-library-for-java.  The source was meant to just be a reference and I'd be glad to take pull requests to get the make file updated in a more generic fashion.
